### PR TITLE
refactor(ui): fix admin layout structure and navigation

### LINKED ISSUE #248: [UI] improve platform settings layout
### Scope
Initial changes are expected to start from:
`ui/src/routes/(auth)/admin/route.tsx`

The final implementation may involve related admin(platform) settings pages

### PR DESCRIPTION
**Pull request by Ruby-rc**
#### What this PR does / why we need it:

Refine the admin layout and navigation structure.

Key changes:

* Adjust admin layout and sidebar structure
* Introduce navigation items for **Users**, **Registries**, and **Replications**
* Add SVG icons for admin navigation
* Add i18n entries for admin pages
* Update `AppLayout` so admin routes use full-width layout

#### Which issue(s) this PR fixes:

Fixes #248

### CODE REVIEW

File: ui/src/routes/(auth)/route.tsx [hunk 1]
```diff
@@ -228,12 +234,12 @@ function AppLayout() {
       >
         <Box
           style={{
-            width: '86vw',
+            width: isAdminRoute ? '100%' : '86vw',
```
Comment (viajes7) [inline ui/src/routes/(auth)/route.tsx]: Suggest splitting into child route page

File: ui/src/routes/(auth)/route.tsx [hunk 2]
```diff
@@ -228,12 +234,12 @@ function AppLayout() {
...
             height: '100%',
-            maxWidth: '1760px',
-            minWidth: '1100px',
-            margin: '0 auto',
-            padding: '0 32px',
+            maxWidth: isAdminRoute ? 'none' : '1760px',
+            minWidth: isAdminRoute ? '0' : '1100px',
+            margin: isAdminRoute ? 0 : '0 auto',
+            padding: isAdminRoute ? 0 : '0 32px',
```
Comment (viajes7) [inline ui/src/routes/(auth)/route.tsx]: The management page has padding at the bottom

File: ui/src/routes/(auth)/admin/route.tsx [hunk 3]
```diff
@@ -21,37 +33,58 @@ export const Route = createFileRoute('/(auth)/admin')({
...
+      label: t('admin.replications'),
+      icon: AdminReplicationsIcon,
+      to: AdminReplicationsRoute.to,
+    },
+  ])
 
   return (
-    <ScrollArea>
-      <Stack gap={0}>
+    <ScrollArea
```
Comment (viajes7) [inline ui/src/routes/(auth)/admin/route.tsx:57]: Image

Unnecessary padding

File: ui/src/routes/(auth)/admin/route.tsx [hunk 4]
```diff
@@ -61,28 +94,54 @@ function AdminNavbar() {
...
 function AdminLayout() {
+  const { t } = useTranslation()
+
   return (
-    <Group
-      align="flex-start"
-      wrap="nowrap"
+    <Flex
+      align="stretch"
       gap={0}
```
Comment (viajes7) [inline ui/src/routes/(auth)/admin/route.tsx]: Unnecessary gap

File: ui/src/routes/(auth)/admin/route.tsx [hunk 5]
```diff
@@ -61,28 +94,54 @@ function AdminNavbar() {
...
-      style={{ height: '100%' }}
+      h="100%"
     >
-      <nav style={{
-        width: 200,
-        flexShrink: 0,
-      }}
+      <Stack
+        component="nav"
+        gap={20}
```
Comment (viajes7) [inline ui/src/routes/(auth)/admin/route.tsx]: Use md for better semantics

File: ui/src/routes/(auth)/admin/route.tsx [hunk 6]
```diff
@@ -61,28 +94,54 @@ function AdminNavbar() {
...
+        w={220}
+        miw={220}
+        h="100%"
```
Comment (viajes7) [inline ui/src/routes/(auth)/admin/route.tsx]: Unnecessary h

File: ui/src/routes/(auth)/admin/route.tsx [hunk 7]
```diff
@@ -61,28 +94,54 @@ function AdminNavbar() {
...
+        px={16}
+        style={{
+          borderInlineEnd: '1px solid var(--mantine-color-default-border)',
```
Comment (viajes7) [inline ui/src/routes/(auth)/admin/route.tsx]: border-color is #DEE2E6

File: ui/src/routes/(auth)/admin/route.tsx [hunk 8]
```diff
@@ -61,28 +94,54 @@ function AdminNavbar() {
...
+        }}
       >
-        {/* Placeholder to display admin routes */}
+        {/* FIXME: color: Gray80 */}
+        <Group
+          gap={6}
+          h={30}
+          wrap="nowrap"
+          pl={4}
+          c="gray.7"
```
Comment (viajes7) [inline ui/src/routes/(auth)/admin/route.tsx:122]: The text color is incorrect

File: ui/src/routes/(auth)/admin/route.tsx [hunk 9]
```diff
@@ -61,28 +94,54 @@ function AdminNavbar() {
...
+        >
+          <SettingsIcon
+            width={30}
```
Comment (viajes7) [inline ui/src/routes/(auth)/admin/route.tsx]: set height={30}

File: ui/src/routes/(auth)/admin/route.tsx [hunk 10]
```diff
@@ -61,28 +94,54 @@ function AdminNavbar() {
...
-      </nav>
-      <div style={{
-        flex: 1,
-        padding: 'var(--mantine-spacing-md)',
-      }}
+      </Stack>
+
+      <Box
+        flex={1}
+        px="md"
```
Comment (viajes7) [inline ui/src/routes/(auth)/admin/route.tsx]: xl

File: ui/src/routes/(auth)/admin/route.tsx [hunk 11]
```diff
@@ -21,37 +33,58 @@ export const Route = createFileRoute('/(auth)/admin')({
 })
 
 function AdminNavbar() {
-  const router = useRouter()
+  const { t } = useTranslation()
   const activeRouteIds = useRouterState({
```
Comment (viajes7) [inline ui/src/routes/(auth)/admin/route.tsx]: perfer useMatchRoute

File: ui/src/routes/(auth)/admin/route.tsx [hunk 12]
```diff
@@ -21,37 +33,58 @@ export const Route = createFileRoute('/(auth)/admin')({
...
+          const Icon = route.icon
           const isActive = activeRouteIds.includes(route.id)
 
           return (
             <NavLink
-              key={route.id}
-              label={route.options.staticData?.navName ?? route.id}
+              key={route.to}
+              label={route.label}
+              leftSection={<Icon fontSize={16} />}
```
Comment (viajes7) [inline ui/src/routes/(auth)/admin/route.tsx]: If you set the width and height of an SVG tag to 1em or specific values, you can indeed control the size of the SVG icon by modifying the parent element's font-size

Comment (viajes7) [reply ui/src/routes/(auth)/admin/route.tsx]: Maybe all our SVGs should be set up this way, so we can control the icon size through fontSize

File: ui/src/routes/(auth)/route.tsx (hunk 1 above)
Comment (Ruby-rc) [reply ui/src/routes/(auth)/route.tsx]: fix

File: ui/src/routes/(auth)/admin/route.tsx (hunk 12 above)
Comment (Ruby-rc) [reply ui/src/routes/(auth)/admin/route.tsx]: fix

File: ui/src/routes/(auth)/admin/route.tsx (hunk 11 above)
Comment (Ruby-rc) [reply ui/src/routes/(auth)/admin/route.tsx]: fix

File: ui/src/routes/(auth)/admin/route.tsx (hunk 9 above)
Comment (Ruby-rc) [reply ui/src/routes/(auth)/admin/route.tsx]: fix

File: ui/src/routes/(auth)/admin/route.tsx (hunk 8 above)
Comment (Ruby-rc) [reply ui/src/routes/(auth)/admin/route.tsx:122]: Will correct this when the color token is ready.

File: ui/src/routes/(auth)/admin/route.tsx (hunk 7 above)
Comment (Ruby-rc) [reply ui/src/routes/(auth)/admin/route.tsx]: fix

File: ui/src/routes/(auth)/admin/route.tsx (hunk 6 above)
Comment (Ruby-rc) [reply ui/src/routes/(auth)/admin/route.tsx]: remove

File: ui/src/routes/(auth)/admin/route.tsx (hunk 5 above)
Comment (Ruby-rc) [reply ui/src/routes/(auth)/admin/route.tsx]: Updated the value to lg.

image

File: ui/src/routes/(auth)/admin/route.tsx (hunk 4 above)
Comment (Ruby-rc) [reply ui/src/routes/(auth)/admin/route.tsx]: remove

File: ui/src/routes/(auth)/admin/route.tsx (hunk 3 above)
Comment (Ruby-rc) [reply ui/src/routes/(auth)/admin/route.tsx:57]: fix

File: ui/src/routes/(auth)/route.tsx (hunk 2 above)
Comment (Ruby-rc) [reply ui/src/routes/(auth)/route.tsx]: fix

Comment (Ruby-rc) [reply ui/src/routes/(auth)/route.tsx]: fix

File: ui/src/routes/(auth)/route.tsx [hunk 13]
```diff
@@ -44,7 +44,10 @@ function AppLogo() {
         gap={8}
         wrap="nowrap"
       >
-        <LogoIcon width={36} />
+        <LogoIcon
+          fontSize={rem(36)}
+          color="#868E96"
```
Comment (viajes7) [inline ui/src/routes/(auth)/route.tsx]: remove color

File: ui/src/routes/(auth)/admin/route.tsx [hunk 14]
```diff
@@ -21,37 +32,64 @@ export const Route = createFileRoute('/(auth)/admin')({
...
+      to: AdminUsersRoute.to,
+    },
+    {
+      id: AdminRegistriesRoute.id,
+      label: t('admin.registries'),
+      icon: AdminRegistriesIcon,
+      to: AdminRegistriesRoute.to,
+    },
+    {
+      id: AdminReplicationsRoute.id,
```
Comment (viajes7) [inline ui/src/routes/(auth)/admin/route.tsx]: useless id

File: ui/src/routes/(auth)/admin/route.tsx [hunk 15]
```diff
@@ -21,37 +32,64 @@ export const Route = createFileRoute('/(auth)/admin')({
...
+    <ScrollArea
+      type="scroll"
+      offsetScrollbars="y"
+      style={{
+        flex: 1,
+        minHeight: 0,
+      }}
+      scrollbarSize={0}
+    >
+      <Stack gap={12} pb={20}>
```
Comment (viajes7) [inline ui/src/routes/(auth)/admin/route.tsx]: use sm、lg

File: ui/src/routes/(auth)/admin/route.tsx [hunk 16]
```diff
@@ -61,28 +99,56 @@ function AdminNavbar() {
...
+        width: 220,
+        breakpoint: '0em',
       }}
+    >
+      <AppShell.Navbar
+        component="nav"
+        mih={0}
+        my="lg"
+        px="md"
+        h="calc(100% - var(--mantine-spacing-lg) * 2)"
```
Comment (viajes7) [inline ui/src/routes/(auth)/admin/route.tsx:114]: set py="lg"

File: ui/src/routes/(auth)/admin/route.tsx (hunk 15 above)
Comment (Ruby-rc) [reply ui/src/routes/(auth)/admin/route.tsx]: fix

File: ui/src/routes/(auth)/admin/route.tsx (hunk 14 above)
Comment (Ruby-rc) [reply ui/src/routes/(auth)/admin/route.tsx]: remove

File: ui/src/routes/(auth)/route.tsx (hunk 13 above)
Comment (Ruby-rc) [reply ui/src/routes/(auth)/route.tsx]: fix
